/** Complete Spanish translation of the customer agreement release candidate. */
const policy = {
  title: "Acuerdo del cliente",
  summary: "Borrador para revisión operativa sobre sus decisiones y el acuerdo directo con el negocio proveedor que usted elija.",
  updated: "30 de septiembre de 2026",
  html: `<section><h2>Información importante sobre el estado actual</h2>
<p>Este Acuerdo del cliente es un borrador operativo. No constituye asesoramiento legal, prueba de cumplimiento ni aprobación para el lanzamiento. El propietario de Tuveloz puede optar por continuar sin contratar un abogado particular, pero esa decisión no elimina ni reduce ninguna obligación impuesta por la ley aplicable. Tuveloz se encuentra actualmente en la etapa de incorporación de proveedores, por lo que los clientes no pueden publicar, reservar, pagar, iniciar ni completar un trabajo real. Cada servicio específico permanece desactivado hasta que se documenten y cumplan sus controles obligatorios de lanzamiento en materia legal, gubernamental, de seguros, impuestos, pagos, seguridad y tecnología.</p></section>
<section><h2>1. Cómo se relaciona este acuerdo con los demás términos</h2>
<p>Este Acuerdo del cliente complementa los <a href="/es/terms">Términos de uso</a>. Se aplica cuando usted publica, revisa, acepta, programa o paga una solicitud de servicio para un vehículo como cliente.</p></section>
<section><h2>2. Su libertad para elegir</h2>
<p>Usted decide si publica una solicitud, qué información incluye, con qué proveedor se comunica, si acepta una cotización y si continúa con un servicio. Tuveloz no le exige seleccionar un proveedor, aceptar una cotización ni comprar un servicio.</p></section>
<section><h2>3. Su autorización y la información que proporciona</h2>
<p>Debe tener autorización para solicitar trabajo en el vehículo y aprobar el lugar donde se realizará el servicio. Proporcione información correcta sobre el vehículo, su estado, los síntomas, la ubicación, el acceso y la seguridad. Informe al proveedor sobre los riesgos o las restricciones que conozca y que puedan afectar el trabajo.</p></section>
<section><h2>4. Elegir un proveedor</h2>
<p>Usted evalúa al proveedor y su cotización con la información que tiene disponible. Cualquier indicación de que Tuveloz ha revisado documentación se limita al proveedor o la persona identificada, al servicio específico, al lugar, al documento y al período de validez indicados; no es una garantía. Según el servicio, Tuveloz puede exigir credenciales gubernamentales, registro comercial, seguros, pruebas de competencia, empleo, supervisión u otra documentación.</p>
<p>Aceptar una cotización crea un acuerdo de servicio directo entre usted y el negocio proveedor responsable. La cotización aceptada, que incluye únicamente mano de obra, y los mensajes definen el trabajo. El negocio proveedor controla la asignación de cualquier empleado o aprendiz patrocinado que haya sido aprobado. Elegir piezas del fabricante original (OEM) o de otros fabricantes solo comunica su preferencia por una pieza que usted compra por separado. No se autoriza trabajo adicional ni un aumento en el precio de la mano de obra sin su consentimiento. Este acuerdo directo no elimina ninguna obligación irrenunciable que la ley imponga a Tuveloz.</p>
<p>TUVELOZ no emplea ni capacita al proveedor, mecánico, aprendiz o empleado del negocio proveedor. Cualquier empleado o aprendiz trabaja para ese negocio proveedor independiente, que le asigna el trabajo y lo supervisa; no trabaja para TUVELOZ ni recibe asignaciones o supervisión de TUVELOZ.</p></section>
<section><h2>5. Lugar del servicio y seguridad</h2>
<p>Elija un lugar donde el trabajo solicitado pueda realizarse de forma legal y razonable. El proveedor puede rechazar o detener el trabajo debido al clima, la exposición al tráfico, las restricciones del inmueble, un terreno inestable, la falta de permiso, información incorrecta sobre el vehículo u otro problema legal o de seguridad. Tuveloz no es un servicio de emergencias ni de rescate en carretera.</p></section>
<section><h2>6. Diagnóstico, inspecciones, piezas y garantías</h2>
<p>Un diagnóstico o una opinión antes de comprar un vehículo puede estar limitado por lo que razonablemente se pueda observar y comprobar en el lugar. No es una inspección estatal oficial, salvo que un proveedor autorizado lo indique expresamente. Tuveloz no vende, consigue, verifica, reembolsa ni procesa pagos por piezas. Usted debe comprar por separado cualquier pieza necesaria. El proveedor debería identificar en los registros del servicio la pieza suministrada por el cliente y cualquier limitación aplicable a la mano de obra. Los derechos y las obligaciones relativos a garantías implícitas o establecidas por ley siguen sujetos a la ley aplicable.</p>
<p>Cada negocio proveedor decide si ofrece una garantía escrita sobre su mano de obra. Tuveloz nunca la exige, porque los proveedores son negocios independientes, no empleados ni agentes de Tuveloz. Cada cotización muestra las condiciones de garantía del proveedor o indica claramente que no se ofrece ninguna, para que usted pueda comparar y elegir. Si selecciona un proveedor que no ofrece garantía sobre su mano de obra, el registro de su aceptación incluye una confirmación expresa de esa decisión. Cualquier garantía que el proveedor ofrezca es una promesa de ese negocio a usted. Tuveloz no la ofrece, respalda ni administra.</p></section>
<section><h2>7. Precio, pago, cancelación y reembolsos</h2>
<p>Los pagos reales de clientes están actualmente desactivados. Cuando se habiliten los pagos, el pago que haga a través de Tuveloz se realizará a TUVELOZ LLC y será procesado por Stripe. El negocio proveedor independiente que usted elija realizará el servicio de su vehículo. Para obtener ayuda con un pago o reembolso, escriba a <a href="mailto:hello@tuveloz.com">hello@tuveloz.com</a>.</p>
<p>Verá la cotización de mano de obra del proveedor, una Tarifa de Servicio al Cliente por separado equivalente al 5% del subtotal del proveedor y el total antes de pagar. Pagará ese total al finalizar el pago. La transferencia al proveedor se realizará después de terminar el trabajo y completar las verificaciones de pago necesarias. La tarifa se suma a su total y no se descuenta de la cotización del proveedor. Usted compra las piezas por separado.</p>
<p>Según la política de cancelación propuesta, un reembolso completo incluye el importe de mano de obra del proveedor y la Tarifa de Servicio al Cliente del 5% de Tuveloz si el proveedor cancela o no se presenta, o si usted cancela antes de que comience el trabajo autorizado. Tuveloz cubre cualquier comisión de procesamiento original que Stripe retenga; no se descuenta de ese reembolso.</p>
<p>El uso en producción todavía requiere documentar el cumplimiento de la ley aplicable y la revisión final del asesor fiscal, procesador, aseguradora y responsables operativos. La <a href="/es/payments">Política de pagos, cancelaciones y reembolsos</a> explica el proceso de pago, los demás casos de cancelación y las protecciones al cliente.</p></section>
<section><h2>8. Problemas con el servicio</h2>
<p>Comunique sin demora al negocio proveedor cualquier problema con la mano de obra, las piezas, la garantía, los retrasos o los bienes afectados. Conserve los mensajes, las autorizaciones, los recibos y las fotos pertinentes. Tuveloz puede ayudar a organizar los registros o revisar un pago aún no liberado si más adelante se habilitan las transacciones reales. Sin embargo, el negocio proveedor sigue siendo responsable del servicio del vehículo y de cualquier garantía que ofrezca expresamente. Tuveloz sigue siendo responsable de su propia conducta y de cualquier obligación que la ley aplicable no le permita excluir.</p></section>
<section><h2>9. Privacidad y uso respetuoso</h2>
<p>Los proveedores que evalúan una solicitud reciben información limitada sobre el trabajo y la zona general. Solo el proveedor que usted seleccione recibe los datos de contacto y la ubicación exacta necesarios para el trabajo. Trate a los proveedores de manera respetuosa y conforme a la ley. No solicite trabajos inseguros, engañosos o ilegales.</p></section>
<section><h2>10. Dejar de usar Tuveloz</h2>
<p>Puede dejar de usar Tuveloz en cualquier momento. Sin embargo, los trabajos aceptados, las obligaciones de pago, los registros de disputas y las disposiciones que deban seguir vigentes continuarán según corresponda. Si este Acuerdo del cliente contradice los Términos generales en un asunto específico del cliente, prevalece este acuerdo.</p></section>`,
};

export default policy;
