/** Complete Spanish translation of app/marketplace-conduct/page.tsx. */
const policy = {
  title: "Política de conducta en el mercado",
  summary: "Borrador de normas de conducta para negocios proveedores, propietarios que realizan el trabajo, aprendices empleados con patrocinio y empleados habituales de negocios proveedores.",
  updated: "4 de agosto de 2026",
  html: `<section><h2>1. Estado de borrador y alcance</h2>
<p>La versión 0.11 es un borrador para revisión operativa. No constituye asesoramiento legal, prueba de cumplimiento, una política activa en producción ni autorización para realizar un servicio. El propietario de Tuveloz puede optar por no contratar un abogado particular, pero todos los requisitos legales aplicables siguen siendo obligatorios. Se aplica a los negocios proveedores, sus propietarios que realizan el trabajo, aprendices, empleados, supervisores y cualquier persona que utilice su cuenta o actúe en su nombre. También se aplican el <a href="/es/provider-agreement">Acuerdo del proveedor</a> y la <a href="/es/provisional-provider-policy">Política de proveedores provisionales y aprendices</a>.</p></section>
<section><h2>2. Identidad, negocio y credenciales veraces</h2>
<p>Use únicamente su propia identidad y la cuenta, nombre comercial, función y credenciales que Tuveloz haya asociado con usted. Mantenga correctos y actualizados los datos de personal, empleo, supervisión, seguro, registro, certificación y vencimientos. No afirme tener licencia, certificación, seguro o aprobación, ser experto ni ser empleado de Tuveloz, salvo que esa afirmación concreta sea verdadera, esté vigente y esté autorizada para mostrarse.</p>
<p>Nunca tome prestados, alquile, comparta ni preste una cuenta, registro, seguro, licencia, supervisor, resultado de verificación o acceso a clientes. Los aprendices patrocinados deben ser empleados remunerados reales de su proveedor patrocinador registrado. Un contratista independiente o trabajador 1099 no puede utilizar el patrocinio de aprendices para obtener acceso.</p></section>
<section><h2>3. Asignación y supervisión controladas por el proveedor</h2>
<p>TUVELOZ no emplea, capacita, patrocina, asigna, dirige, disciplina ni supervisa a proveedores o a su personal. Un negocio proveedor separado debe cumplir esas funciones respecto de cada empleado o aprendiz que incluya en su lista de personal.</p>
<p>El negocio proveedor debe asignar a la persona que realizará el trabajo y al supervisor requerido. Un aprendiz no puede cotizar por su cuenta, aceptar un trabajo, asignarse a sí mismo, sustituir a otra persona, supervisar a un aprendiz ni recibir pagos directos de Tuveloz. Un empleado habitual solo puede realizar trabajos asignados por el negocio proveedor y dentro de su habilitación vigente.</p>
<p>La persona asignada debe coincidir con la que se informó al cliente y registró su llegada al trabajo. Una sustitución requiere aprobación del proveedor, revisión de habilitación, información actualizada y nueva aceptación del cliente cuando corresponda. La supervisión directa exige que el supervisor aprobado esté físicamente presente, pueda intervenir y complete cada control y aprobación requeridos.</p></section>
<section><h2>4. Alcance exacto, cotizaciones y autorización del cliente</h2>
<p>Describa con veracidad el servicio exacto, mano de obra, piezas, supuestos, exclusiones, horario, cargos, impuestos y garantía del proveedor. El trabajo debe mantenerse dentro de un código de servicio específico habilitado. El trabajo adicional o un cambio de pieza, persona, precio o alcance sustancial requiere aprobación del negocio proveedor y autorización documentada del cliente antes de continuar.</p>
<p>No diagnostique, inspeccione, repare, certifique ni haga afirmaciones sobre seguridad, emisiones, valor, garantía o inspección oficial fuera del alcance habilitado. Detenga y actualice o rechace el trabajo cuando las condiciones reales difieran sustancialmente de la solicitud.</p></section>
<section><h2>5. Seguridad, propiedad y obligación de detener el trabajo</h2>
<p>Siga el procedimiento aprobado para el servicio, las reglas del lugar de trabajo y de carretera, los controles de elevación y herramientas, las especificaciones de piezas, las restricciones sobre pruebas de conducción, los requisitos ambientales y de eliminación de residuos y el plan de incidentes. Proteja el vehículo, las llaves, la propiedad y las pertenencias del cliente.</p>
<p>Detenga el trabajo ante tráfico inseguro, suelo inestable, clima severo, riesgo de incendio o combustible, equipos dañados, sistemas de alto voltaje imprevistos, violencia, falta de permiso, un lugar no aprobado o cualquier condición ajena al procedimiento autorizado. No conduzca ni pruebe el vehículo de un cliente salvo que el proceso exacto, la persona, el seguro y la autorización del cliente lo permitan.</p></section>
<section><h2>6. Trato respetuoso y legal</h2>
<p>Trate profesionalmente a clientes, otros proveedores, personal de Tuveloz y al público. No amenace, acose, persiga, tome represalias, coaccione, discrimine ilegalmente, incurra en conductas sexuales o de odio, cometa fraude, trabaje bajo efectos que reduzcan su capacidad, posea armas ilegales ni provoque confrontaciones inseguras. Retírese y contacte a los servicios de emergencia apropiados cuando lo exija la seguridad inmediata.</p>
<p>Las reseñas y los registros de servicio deben reflejar hechos reales. No intercambie beneficios por reseñas engañosas, suprima quejas veraces, suplante a un cliente ni tome represalias por comentarios o denuncias legales.</p></section>
<section><h2>7. Datos de clientes y comunicaciones</h2>
<p>Use la información de contacto, ubicación, vehículo, fotos, mensajes y pagos del cliente solo para el servicio seleccionado, asistencia, seguridad, registros obligatorios u otro fin legal descrito en la Política de privacidad. No la venda, publique, use para publicidad ajena al servicio, solicite datos de identidad innecesarios ni la conserve más tiempo del razonablemente necesario.</p>
<p>Mantenga en el sistema aprobado las comunicaciones sustanciales sobre alcance, asignación, autorización, precio, garantía e incidentes para que el negocio proveedor, el cliente y Tuveloz puedan conservar los registros necesarios. No cargue contraseñas, datos completos de tarjetas de pago ni documentos migratorios innecesarios.</p></section>
<section><h2>8. Integridad en pagos, facturación, garantías y nómina</h2>
<p>No redirija trabajos de la plataforma a cuentas no declaradas, solicite pagos no autorizados, oculte cargos adicionales, presente registros falsos de finalización, manipule reembolsos o contracargos ni utilice indebidamente el método de pago del cliente. El negocio proveedor controla y es responsable de la factura, garantía del servicio, registros obligatorios y aprobación final.</p>
<p>Tuveloz transfiere el pago de un trabajo habilitado al negocio proveedor, no a su aprendiz o empleado. El negocio proveedor es responsable de salarios, nómina, retenciones, impuestos, beneficios y cobertura de trabajadores. Ningún arreglo fuera de la plataforma convierte a un empleado patrocinado en un aprendiz 1099 legal ni permite compartir credenciales.</p></section>
<section><h2>9. Incidentes y cooperación</h2>
<p>Informe con prontitud lesiones, daños a vehículos o propiedad, incendios, derrames, amenazas de clientes, contactos de la policía o autoridades reguladoras, pérdida de bienes, fallas de equipos, piezas incorrectas, sospechas de fraude, vencimientos de credenciales o seguros y peligros de combustible o alto voltaje. Conserve cotizaciones, autorizaciones, mensajes, fotos, asignaciones, controles de supervisión, facturas, garantías y avisos a aseguradoras.</p>
<p>Coopere con veracidad en revisiones razonables de seguridad, pagos, seguros, credenciales, privacidad o conducta. No altere, elimine, fabrique ni coordine registros falsos, ni presione a otras personas para que oculten información pertinente.</p></section>
<section><h2>10. Revisión y aplicación de las normas</h2>
<p>Tuveloz puede bloquear un servicio, persona, negocio proveedor, pago o cuenta mientras revisa una preocupación creíble. Según la gravedad y la ley aplicable, las medidas pueden incluir orientación, advertencias, pruebas adicionales, retiro de un servicio, cancelación, revisión de pagos, suspensión o terminación. El bloqueo inmediato es apropiado ante un requisito legal o de seguro incumplido, o un riesgo grave de seguridad, identidad, fraude o credenciales.</p>
<p>Cuando sea razonablemente práctico y jurídicamente apropiado, Tuveloz explicará el motivo y proporcionará un medio para enviar correcciones o registros pertinentes. Las revisiones deben utilizar criterios objetivos y aplicados de forma coherente. Una apelación no restablece el acceso mientras siga incumplido un requisito obligatorio.</p></section>
<section><h2>11. Requisitos de activación y obligaciones de Tuveloz</h2>
<p>Cada servicio específico permanece desactivado hasta que se documenten y cumplan sus requisitos federales, de Maryland, locales, gubernamentales y de agencias; el corredor de seguros de Tuveloz confirme la cobertura para la operación exacta; y se implementen las vías, pruebas, exclusiones, supervisión, ubicación, gestión de incidentes y controles operativos del servicio. Los servicios candidatos y las denominaciones de políticas no constituyen permiso para trabajar.</p>
<p>Las obligaciones del proveedor, el seguro y la aplicación de normas del mercado no garantizan que Tuveloz carezca de responsabilidad. Nada de esta política excluye las responsabilidades de Tuveloz sobre su mercado, pagos, privacidad u otras impuestas por la ley aplicable.</p></section>`,
};

export default policy;
