/** Complete Spanish translation of app/payments/page.tsx. */
const policy = {
  title: "Política de pagos, cancelaciones y reembolsos",
  summary: "Borrador para revisión operativa de los precios, pagos, transferencias, cancelaciones y protecciones al cliente propuestos.",
  updated: "4 de agosto de 2026",
  html: `<section><h2>Información importante sobre el estado actual</h2>
<p>Tuveloz está actualmente en la etapa de incorporación de proveedores. Los pagos reales de clientes, cobros, transferencias a proveedores, finalización de trabajos y pagos al proveedor están desactivados. Este borrador operativo está destinado a la revisión del propietario, contador público certificado o asesor fiscal, procesador de pagos, aseguradora y responsables de seguridad e implementación. No constituye asesoramiento legal o fiscal, prueba de cumplimiento ni aprobación para el lanzamiento. El propietario de Tuveloz puede optar por no contratar un abogado particular, pero toda obligación impuesta por la ley aplicable sigue siendo obligatoria. Este borrador no resuelve las responsabilidades sobre el comerciante registrado responsable de la transacción, impuestos, flujo de fondos, reembolsos, contracargos o reservas.</p></section>
<section><h2>1. Precio mostrado antes del pago</h2>
<p>Las solicitudes de clientes y los pagos todavía no están abiertos. La configuración actual propone un cargo de servicio al cliente equivalente al 5 % del subtotal cotizado por el proveedor. Si se aprueban definitivamente ese precio y el proceso de pago, el cliente deberá ver claramente el subtotal del proveedor, el cargo de servicio por separado y el total antes de decidir si continúa. Tuveloz no debe añadir trabajo a una cotización aceptada. Todo importe del proveedor procesado por Tuveloz corresponde únicamente a mano de obra; se prohíben las piezas suministradas por el proveedor, su reembolso, sus impuestos y cualquier otro cargo por piezas. Un cambio en el alcance o precio de la mano de obra requiere aprobación expresa del cliente antes de efectuar un cargo adicional.</p></section>
<section><h2>2. Precios del proveedor y cargo de servicio al cliente propuesto</h2>
<p>Los negocios proveedores fijan sus propias cotizaciones, exclusivamente de mano de obra. El cliente compra por separado cualquier pieza necesaria, que no se incluye en el subtotal del proveedor. El diseño propuesto registra por separado el subtotal de mano de obra aceptado y un cargo de servicio al cliente del 5 % por el apoyo del mercado y la transacción. El porcentaje, cálculo de transferencias, ajustes y tratamiento contable siguen sujetos al cumplimiento documentado de la ley aplicable y a la aprobación final del contador público certificado o asesor fiscal, procesador, aseguradora y responsables operativos. La configuración del producto por sí sola no determina una clasificación legal o fiscal ni promete un pago concreto al proveedor.</p></section>
<section><h2>3. Proceso de pago propuesto mediante Stripe</h2>
<p>El producto propuesto utiliza páginas de pago alojadas por Stripe para que Tuveloz no reciba ni almacene números completos de tarjetas o cuentas bancarias. Toda configuración de cargos, transferencias o cuentas conectadas permanece en pruebas y debe coincidir con el acuerdo final del procesador y el modelo legal y contable aprobado antes de utilizarse en producción.</p>
<p>Las denominaciones técnicas del procesador o los movimientos de fondos no determinan por sí solos quién es el comerciante registrado responsable de la transacción, quién debe un impuesto, si alguien actúa como representante ni qué obligaciones legales se aplican. Estas cuestiones deben resolverse conforme a la ley aplicable con la revisión final del contador público certificado o asesor fiscal, procesador, aseguradora y responsables operativos. Si se habilitan los pagos, el negocio proveedor seleccionado seguirá siendo quien acepta y cumple el acuerdo del servicio para vehículos y responde por cualquier garantía de mano de obra que ofrezca expresamente. Tuveloz no procesa pagos por piezas; el cliente compra las piezas por separado. Nada de este borrador decide derechos o responsabilidades de garantía irrenunciables.</p>
<p>Los términos y la política de privacidad de Stripe también se aplican a sus servicios. Nada del proceso propuesto elimina obligaciones de pago, privacidad, protección al consumidor u otras que la ley aplicable imponga a Tuveloz.</p></section>
<section><h2>4. Autorización, cobro y recibos</h2>
<p>Actualmente no se puede autorizar un pago real. Si se aprueban los pagos en producción, elegir el botón de pago autorizará únicamente el total mostrado con la cotización aceptada y las condiciones divulgadas vigentes. Un pago completado sería prueba de pago, no de que el servicio haya terminado o el vehículo sea seguro para conducir. Stripe o el emisor de la tarjeta pueden rechazar, revisar o revertir una transacción conforme a sus propias reglas.</p></section>
<section><h2>5. Transferencias propuestas a proveedores</h2>
<p>Actualmente no hay transferencias a proveedores en producción. El proceso propuesto retendría una transferencia hasta que el trabajo cumpla los controles del servicio exacto, proveedor, persona que realiza el trabajo, supervisión, finalización y autorización de pago. Una transferencia aún no liberada podría pausarse mientras Tuveloz revisa una cancelación, cargo duplicado, señal de fraude, queja de servicio, disputa, prueba vencida o registro incoherente.</p>
<p>Los plazos definitivos de transferencia, derechos de ajuste, reservas y responsabilidades por cargos del procesador, reembolsos, disputas y contracargos deben aprobarse y exponerse claramente antes de operar en producción. Tuveloz no describirá el proceso propuesto como depósito bancario, fideicomiso o depósito en garantía salvo que esa descripción sea correcta conforme a la ley aplicable y el procesador la apruebe.</p></section>
<section><h2>6. Protecciones propuestas ante cancelaciones</h2>
<p>Las siguientes son protecciones básicas propuestas para revisión final. Todavía no son promesas generales de reembolso vigentes y siguen sujetas a la ley aplicable, las reglas del procesador, los hechos documentados del trabajo y la política final mostrada antes del pago:</p>
<ul><li>La regla propuesta ofrecería un reembolso completo del importe pagado por el servicio si el proveedor cancela, no se presenta o no puede realizar el servicio aceptado.</li>
<li>La regla propuesta ofrecería un reembolso completo si el cliente cancela antes de comenzar la mano de obra autorizada.</li>
<li>Si ya comenzó la mano de obra autorizada, el reembolso podría excluir el valor documentado del trabajo autorizado ya realizado, pero solo en la medida permitida por la ley. Tuveloz no cobra ni reembolsa piezas que el cliente haya comprado por separado.</li>
<li>Un proveedor puede detener el trabajo por un lugar inseguro o ilegal, falta de autorización o información del trabajo sustancialmente incorrecta. Cualquier cargo o reembolso dependerá del trabajo y los costos autorizados documentados, la ley aplicable y los registros disponibles.</li></ul>
<p>El proceso final no debe limitar derechos de cancelación, reembolso u otros recursos que la ley aplicable no permita limitar a las partes.</p></section>
<section><h2>7. Reembolsos y correcciones</h2>
<p>Si se habilitan los pagos reales, Tuveloz revisará los reportes de cargos de la plataforma duplicados, no autorizados o mal calculados y realizará las correcciones exigidas por la ley aplicable, las reglas del procesador o la política final aceptada. Un reembolso aprobado normalmente se devolvería al método de pago original, salvo que la ley o la red de pago exijan otra cosa. El banco o emisor de la tarjeta controla cuándo aparece el abono. Nada de lo aquí indicado limita un recurso irrenunciable del consumidor.</p></section>
<section><h2>8. Quejas de servicio, disputas y contracargos</h2>
<p>Escriba con prontitud a <a href="mailto:hello@tuveloz.com?subject=Payment%20Issue">hello@tuveloz.com</a> e incluya el trabajo, proveedor, importe, solución solicitada y mensajes, aprobaciones, facturas, recibos o fotos pertinentes. Tuveloz puede pedir registros a ambas partes y pausar una transferencia aún no liberada mientras revisa el asunto.</p>
<p>El cliente conserva el derecho a contactar al emisor de su tarjeta. Los contracargos se deciden conforme a las reglas de la red y del emisor de la tarjeta, y pueden descontarse del saldo de la plataforma Tuveloz según la configuración final de pagos. El retraso, ajuste, reversión o recuperación de una transferencia al proveedor debe ajustarse al acuerdo final del procesador, las condiciones aceptadas por el proveedor, los hechos documentados y la ley aplicable. Este borrador no crea un derecho automático de recuperación ni garantiza el resultado de una disputa.</p></section>
<section><h2>9. Impuestos y registros</h2>
<p>La arquitectura de pagos propuesta no determina quién debe cobrar, declarar, retener o pagar un impuesto específico. Tuveloz obtendrá orientación final de un contador público certificado o asesor fiscal cualificado, documentará los requisitos legales aplicables y configurará los pagos y declaraciones conforme a las responsabilidades impuestas por la ley. Los negocios proveedores siguen siendo responsables de mantener registros comerciales correctos y de las obligaciones que la ley les imponga. Clientes y proveedores deben conservar cotizaciones, aprobaciones, facturas, recibos y registros del servicio.</p></section>
<section><h2>10. Preparación para pagos en producción</h2>
<p>El procesamiento de pagos reales permanece desactivado. Solo puede habilitarse después de que Tuveloz documente el cumplimiento de la ley y las reglas gubernamentales aplicables; registre las aprobaciones necesarias del contador público certificado o asesor fiscal, aseguradora y procesador; confirme el análisis del comerciante registrado y de los impuestos sin depender de una denominación técnica; adopte controles claramente divulgados de cargos, cancelaciones, reembolsos, disputas, contracargos, reservas, seguridad y conservación de registros; y verifique la habilitación del servicio exacto, negocio proveedor, persona que realizará el trabajo, supervisor cuando sea necesario y etapa del trabajo. Ningún cambio técnico puede anular estos controles.</p></section>`,
};

export default policy;
