/** Complete Spanish translation of app/privacy/page.tsx. */
const policy = {
  title: "Política de privacidad",
  summary: "Qué información recopila Tuveloz, por qué la necesita, quién la recibe y qué opciones tiene usted.",
  updated: "6 de agosto de 2026",
  html: `<section><h2>1. Alcance y fuentes</h2>
<p>Esta política se aplica a la información personal que TUVELOZ LLC trata a través de su sitio web, cuentas, solicitudes de clientes, solicitudes de proveedores, páginas públicas de proveedores, asistencia, comunicaciones y registros de pagos. Recibimos información de usted, de la otra parte de un trabajo, de los prestadores que operan la plataforma y de los registros creados al usar Tuveloz.</p></section>
<section><h2>2. Información que recopilamos</h2>
<ul><li>Identificadores y datos de cuenta, como nombre, correo electrónico, función, hash de contraseña, registros de sesiones e inicios de sesión, idioma y mensajes de asistencia.</li>
<li>Número de teléfono, solo si lo añade para iniciar sesión mediante mensajes de texto: el número, su estado de verificación y los registros de los códigos de un solo uso enviados. El código se almacena únicamente como un hash. Los mensajes se utilizan exclusivamente para los códigos de inicio de sesión y verificación que solicite, según los <a href="/sms-terms">Términos de SMS (en inglés)</a>, nunca para publicidad.</li>
<li>Datos de trabajos de clientes, como información del vehículo o un VIN que decida proporcionar, servicios solicitados, zona general, dirección exacta del servicio cuando sea necesaria, fotos, registros del estado del vehículo, cotizaciones elegidas, mensajes, estado del trabajo y reseñas.</li>
<li>Datos del proveedor, como nombre y ubicación del negocio, nombre de quien realizará el trabajo, áreas y opciones de servicio, experiencia, respuestas sobre seguro, credenciales legalmente aplicables, estado y referencias de verificación de identidad, decisiones de verificación, contenido del perfil e identificadores de cuentas conectadas de Stripe.</li>
<li>Datos de transacciones, como importes mostrados, estado del pago, correo para recibos, reembolsos, disputas, estado de transferencias e identificadores de transacciones de Stripe.</li>
<li>Datos técnicos y de seguridad necesarios para ofrecer el sitio, proteger cuentas, prevenir abusos, investigar errores y mantener registros de auditoría.</li></ul>
<p>Stripe recopila información de tarjetas de pago, identidad, cobros, impuestos y cuentas bancarias en páginas alojadas por Stripe. La verificación de documento y selfie de Stripe Identity captura imágenes de un documento oficial con foto y del rostro de la persona, extrae información de identidad como nombre y fecha de nacimiento y utiliza comparación biométrica para determinar si la selfie coincide con el documento. Stripe solicita su propio consentimiento en ese proceso y maneja los datos conforme a sus condiciones de privacidad. Tuveloz no recibe ni almacena números completos de tarjetas o cuentas bancarias.</p>
<p>La aplicación de Tuveloz procesa el nombre y la fecha de nacimiento verificados únicamente en memoria para compararlos con la persona designada para realizar el trabajo y confirmar que sea adulta. Tuveloz guarda la referencia de la sesión o informe de Stripe, la decisión, la fecha de revisión y la fecha de validez, pero no guarda el nombre verificado, fecha de nacimiento, número de identificación, imagen del documento, selfie ni identificador biométrico. Los administradores autorizados de Tuveloz pueden tener acceso a información de identidad en el panel restringido de Stripe cuando sea razonablemente necesario para verificar, revisar fraude o seguridad, atender una solicitud de privacidad o cumplir una obligación legal.</p></section>
<section><h2>3. Para qué usamos la información</h2>
<p>Usamos la información para crear y proteger cuentas; recibir solicitudes; determinar áreas de servicio y habilitación; conectar solicitudes con proveedores; presentar cotizaciones y actualizaciones de trabajos; verificar credenciales legalmente aplicables; procesar y conciliar pagos; publicar contenido de perfil elegido por el proveedor; prevenir fraude; resolver asuntos de asistencia, seguridad, privacidad y pagos; mantener registros legales, fiscales y contables; y mejorar Tuveloz.</p>
<p>Tuveloz limita la recopilación a la información razonablemente necesaria y proporcional a esos fines. No usamos información personal para un fin sustancialmente ajeno sin aviso y sin el consentimiento que exija la ley.</p></section>
<section><h2>4. Ubicación exacta y divulgación por etapas</h2>
<p>Los proveedores que deciden si cotizan reciben información limitada del trabajo y la zona general de servicio, no el correo privado ni la dirección exacta del cliente. Después de que el cliente selecciona un proveedor, este recibe los datos de contacto y ubicación exacta razonablemente necesarios para organizar el trabajo aceptado. El cliente recibe la información pertinente del negocio proveedor y sus datos de contacto.</p>
<p>Si introduce una dirección exacta para un servicio en su ubicación, indica a Tuveloz que la utilice y comparta con el proveedor seleccionado únicamente para organizar y apoyar ese servicio. Cuando esté disponible, puede elegir acudir al local del proveedor y evitar proporcionar una dirección de servicio del cliente.</p></section>
<section><h2>5. Prestadores de servicios y otras divulgaciones</h2>
<ul><li>Stripe procesa pagos, cuentas conectadas, transferencias, reembolsos, disputas, riesgos de pago y verificación alojada de identidad del proveedor mediante documento y selfie.</li>
<li>Cloudflare proporciona alojamiento, seguridad, base de datos y almacenamiento privado de imágenes.</li>
<li>Cloudmersive recibe archivos de pruebas de proveedores en cuarentena únicamente para detectar programas maliciosos y contenido inseguro antes de que Tuveloz permita revisarlos o descargarlos.</li>
<li>Resend entrega correos electrónicos transaccionales.</li>
<li>Los asesores profesionales pueden recibir información cuando sea razonablemente necesaria para trabajos contables, de seguro, seguridad o legales, sujetos a obligaciones apropiadas.</li>
<li>Podemos divulgar información para cumplir la ley, procesos legales válidos, reglas de redes de pago o una necesidad de buena fe de proteger a usuarios, derechos, propiedad o seguridad de la plataforma.</li>
<li>La información puede transferirse como parte de una fusión, financiación, adquisición, reorganización o venta, con sujeción a esta política y a la ley aplicable.</li></ul></section>
<section><h2>6. Sin venta, publicidad conductual ni decisiones exclusivamente automatizadas</h2>
<p>Tuveloz no vende información personal. Actualmente no utiliza información personal para publicidad dirigida entre sitios ni decisiones exclusivamente automatizadas que produzcan efectos legales o de importancia similar. Las páginas públicas de proveedores omiten el correo privado y la dirección exacta, y las reseñas públicas muestran el nombre y la inicial del apellido.</p></section>
<section><h2>7. Conservación</h2>
<p>Conservamos la información solo durante el tiempo razonablemente necesario para el fin de su recopilación, la cuenta y el servicio, seguridad, disputas, reembolsos y contracargos, prevención del fraude, registros fiscales y contables y otras obligaciones legales. El plazo depende del tipo de registro, de si el trabajo o la cuenta siguen activos y de si hay un asunto legal o de pago pendiente. Eliminamos o desidentificamos la información cuando deja de ser razonablemente necesaria, salvo que la ley permita o exija conservarla.</p>
<p>Stripe controla la conservación de imágenes de identidad, datos extraídos e identificadores biométricos conforme a sus condiciones de privacidad y a las opciones que presenta en su proceso. Tuveloz puede pedir a Stripe que suprima los datos de una sesión de verificación que cumpla las condiciones cuando ya no sean necesarios, con sujeción a los requisitos de fraude, seguridad, disputas y conservación legal. Una referencia limitada de verificación y auditoría de Tuveloz puede conservarse para esos fines incluso después de suprimir los datos alojados en Stripe.</p></section>
<section><h2>8. Sus opciones y solicitudes de privacidad</h2>
<p>Con sujeción a la ley aplicable, puede pedir que Tuveloz confirme si trata su información personal; proporcione acceso o una copia portátil; corrija inexactitudes; elimine información; limite ciertos usos; o identifique las categorías de terceros que recibieron información personal. También puede excluirse si Tuveloz comienza posteriormente a vender información, utilizarla para publicidad dirigida o realizar perfiles sujetos a esos derechos.</p>
<p>Los clientes y proveedores que hayan iniciado sesión pueden usar el <a href="/privacy-center">Centro de privacidad de Tuveloz (en inglés)</a> para descargar una copia de sus datos de cuenta, corregir el perfil, gestionar opciones de correo, enviar una solicitud verificada, consultar su estado, retirar una solicitud abierta o apelar una decisión finalizada o denegada.</p>
<p>Quienes no puedan iniciar sesión pueden escribir a <a href="mailto:hello@tuveloz.com?subject=Privacy%20Request">hello@tuveloz.com</a> con el asunto «Privacy Request». Podemos verificar la identidad y la autoridad antes de actuar. Responderemos dentro del plazo exigido por la ley aplicable y explicaremos cualquier denegación. Las solicitudes de privacidad son gratuitas, y Tuveloz no discriminará a nadie por ejercer un derecho aplicable.</p>
<p>Un proveedor que no desee utilizar una selfie u otra verificación biométrica puede contactar a <a href="mailto:hello@tuveloz.com?subject=Alternative%20Identity%20Verification">hello@tuveloz.com</a> antes de iniciar Stripe Identity para solicitar un método externo no biométrico disponible. Solicitar una alternativa no concede acceso a trabajos ni elimina requisitos de identidad, edad, credenciales o servicios.</p></section>
<section><h2>9. Seguridad</h2>
<p>Tuveloz utiliza hashes de contraseñas, códigos de un solo uso con vencimiento, límites de solicitudes y bloqueos, cookies de sesión seguras, controles de acceso por función y por registro, imágenes privadas restringidas, webhooks firmados de Stripe, HTTPS, encabezados de seguridad y acceso administrativo limitado. Ningún sistema puede garantizar seguridad absoluta. Informe con prontitud cualquier sospecha de acceso no autorizado a <a href="mailto:hello@tuveloz.com?subject=Security%20Report">hello@tuveloz.com</a>.</p>
<p>La página pública de <a href="/system-status">Estado del sistema de Tuveloz (en inglés)</a> indica si la versión de la aplicación, la conexión con la base de datos y el esquema operativo requerido están listos. No expone credenciales, registros privados, cantidades de usuarios, detalles de pagos ni controles internos de seguridad.</p></section>
<section><h2>10. Cookies y almacenamiento en el dispositivo</h2>
<p>Tuveloz utiliza cookies esenciales para proteger las sesiones iniciadas y almacenamiento en el dispositivo para preferencias como el idioma. Actualmente no usamos cookies publicitarias. Si eso cambia, primero actualizaremos esta política y los mecanismos de elección exigidos por la ley.</p></section>
<section><h2>11. Edad mínima, cambios y contacto</h2>
<p>Las cuentas, solicitudes de trabajos, solicitudes de proveedores y pagos de Tuveloz son para adultos. Tuveloz no recopila deliberadamente información de cuenta de menores de 18 años. Los cambios importantes se publicarán con una nueva fecha y se presentarán para consentimiento cuando la ley lo exija.</p>
<p>Contacte a TUVELOZ LLC en <a href="mailto:hello@tuveloz.com">hello@tuveloz.com</a> sobre esta política o una solicitud de privacidad.</p></section>`,
};

export default policy;
