/** Complete Spanish translation of app/provisional-provider-policy/page.tsx. */
const policy = {
  title: "Política de proveedores provisionales y aprendices",
  summary: "Borrador que deniega el acceso por defecto para propietarios de negocios nuevos que trabajan por cuenta propia, aprendices empleados con patrocinio y empleados habituales de negocios proveedores.",
  updated: "4 de agosto de 2026",
  html: `<section><h2>1. Estado y regla principal</h2>
<p>La versión 0.11 es un borrador para revisión operativa. No constituye asesoramiento legal, prueba de cumplimiento, una política activa en producción, una determinación de que un servicio sea legal o esté asegurado, ni permiso para trabajar para clientes. El propietario de Tuveloz puede optar por no contratar un abogado particular, pero todos los requisitos legales aplicables siguen siendo obligatorios. Esta política debe revisarse junto con el <a href="/es/provider-agreement">Acuerdo del proveedor</a> y la <a href="/es/marketplace-conduct">Política de conducta en el mercado</a>.</p>
<p>Esta política deniega el acceso por defecto. Cada servicio específico permanece desactivado hasta que se documenten y cumplan sus requisitos federales, de Maryland, locales, gubernamentales y de agencias; el corredor de seguros de Tuveloz confirme la cobertura de la operación exacta; y se implementen en producción la vía de relación, pruebas, exclusiones, supervisión, ubicación, gestión de incidentes y procedimiento operativo. Ninguna política puede garantizar que Tuveloz carezca de toda responsabilidad.</p></section>
<section><h2>2. Las credenciales del negocio y la autorización de trabajo son distintas</h2>
<p>Las reglas de Maryland y locales pueden exigir que el negocio proveedor cuente con registros, licencias, permisos o certificados de reparación, mantenimiento, remolque, especialidad, impuestos, medioambiente u otros para el trabajo exacto y el lugar. Un empleado real puede trabajar a través del negocio registrado únicamente dentro de la vía de empleados y los controles de servicio aprobados. Esto no permite que un contratista ajeno utilice las credenciales del negocio.</p>
<p>Estas credenciales comerciales y de servicio son distintas de la autorización legal de una persona para trabajar en Estados Unidos. El negocio proveedor empleador, no una revisión de credenciales de la plataforma, debe completar su propio proceso legal de contratación y autorización de trabajo. Tuveloz no debe recopilar documentos migratorios innecesarios en su sistema general de documentos de proveedores.</p></section>
<section><h2>3. Vía A: propietario de un negocio nuevo que trabaja por cuenta propia</h2>
<p>Una persona adulta que inicia un negocio puede solicitar ingreso como propietario que realiza el trabajo de un negocio proveedor establecido de forma independiente. El propietario verificado y quien realiza el trabajo deben ser la misma persona. Antes de activar posteriormente cualquier servicio, el negocio debe contar con los registros que le correspondan, configuración fiscal y de cobros, seguro aprobado por el corredor, competencia y herramientas para el servicio exacto, lugar de trabajo y proceso de eliminación de residuos legales, acuerdos aceptados y todos los demás requisitos de la matriz aprobada.</p>
<p>La declaración de no tener empleados solo puede utilizarse cuando sea correcta y esté aprobada. Si el negocio emplea a alguien, debe aportar los registros de personal, empleo, compensación laboral y seguros requeridos. Una tarea sencilla no está automáticamente exenta de los requisitos aplicables a negocios de reparación.</p></section>
<section><h2>4. Vía B: aprendiz empleado con patrocinio</h2>
<p>Un aprendiz patrocinado debe ser un empleado remunerado real de un negocio proveedor registrado. Esta vía no tiene una modalidad 1099 o de contratista independiente. El negocio patrocinador sigue siendo el proveedor responsable en la cotización, pago, recibo, factura y garantía, y debe mantener al aprendiz en su lista de personal aprobada y vigente, con registros de empleo, compensación laboral, seguro y del servicio específico.</p>
<p>TUVELOZ no es el empleador del aprendiz ni el negocio proveedor patrocinador, y no contrata, capacita, asigna, dirige, disciplina ni supervisa al aprendiz. El negocio proveedor separado debe cumplir todas las funciones de empleador, capacitación, supervisión, seguro, nómina y asignación.</p>
<p>El negocio patrocinador acepta y asigna el trabajo, designa a un supervisor habilitado, controla herramientas, métodos, horarios, formación y disciplina, prepara o aprueba la cotización y autorización del cliente, supervisa y revisa el trabajo, emite o aprueba la factura y garantía del proveedor y da su aprobación antes de finalizar el trabajo o liberar el pago. Tuveloz paga al negocio proveedor; este es responsable de salarios, nómina, retenciones, impuestos, beneficios y cobertura de trabajadores.</p></section>
<section><h2>5. Vía C: empleado habitual de un negocio proveedor</h2>
<p>Un negocio proveedor registrado de nivel estándar o especializado puede asignar a un empleado real que no sea aprendiz únicamente cuando esté vinculado al negocio mediante registros vigentes de personal y empleo, compensación laboral y seguro aplicable, competencia para el servicio exacto y una asignación controlada por el proveedor. El negocio sigue siendo el proveedor del cliente y controla factura, garantía, finalización, pago al proveedor y nómina.</p>
<p>Esta vía no está disponible para cuentas que solo han presentado una solicitud, el nivel de aprendiz patrocinado ni el nivel independiente provisional, y no puede utilizarse para eludir la supervisión inicial o requisitos de especialidad. La relación laboral real, no la etiqueta elegida en una cuenta, determina la clasificación legal.</p></section>
<section><h2>6. Prohibición de utilizar credenciales ajenas</h2>
<p>Ningún contratista independiente o trabajador ajeno puede usar, alquilar, tomar prestados, compartir ni alegar cobertura mediante el registro, licencia, seguro, supervisor, cuenta, lista de personal o identidad de otro proveedor simplemente para acceder a trabajos. Un negocio proveedor no puede crear un «patrocinio» solo en papel, una relación de nómina falsa ni una asignación nominal para eludir obligaciones de registro, clasificación, impuestos, compensación laboral, seguro o supervisión.</p>
<p>Si una persona no es un empleado real de la vía B o C, debe cumplir de forma independiente la vía A antes de que pueda habilitarse cualquier trabajo remunerado de reparación, mantenimiento, revisión, diagnóstico, instalación de piezas, servicio de fluidos u otro trabajo regulado.</p></section>
<section><h2>7. Servicios limitados candidatos, todavía no activos</h2>
<p>Después de documentar los requisitos legales y de agencias obligatorios y obtener la aprobación de cobertura para la operación exacta de la aseguradora, Tuveloz puede considerar códigos de servicio definidos de forma limitada para los siguientes trabajos. Todos están actualmente desactivados y sujetos a sus propias reglas de registro, competencia, herramientas, seguro, ubicación, medioambiente, exclusiones, registros y supervisión:</p>
<ul><li>Lectura de códigos OBD-II sin modificaciones e informe objetivo de los códigos.</li>
<li>Informes visuales o fotográficos del estado del vehículo solicitados por el cliente, que no constituyan inspección oficial, tasación, garantía ni determinación de seguridad.</li>
<li>Cambio de plumillas del limpiaparabrisas.</li>
<li>Cambio limitado de filtros de aire del motor o de la cabina.</li>
<li>Cambio de determinados focos exteriores convencionales reemplazables.</li>
<li>Relleno de líquido limpiaparabrisas y, con aprobación separada, de aceite del motor.</li>
<li>Procedimientos aprobados de arranque con corriente y cambio de baterías de 12 voltios.</li>
<li>Instalación de una rueda de repuesto temporal con controles estrictos de elevación.</li>
<li>Limpieza básica aprobada sin agua o con contención de residuos.</li>
<li>Servicio de aceite y filtro con patrocinio en un local aprobado del proveedor, con supervisión directa y proceso de eliminación de residuos requeridos.</li></ul>
<p>Los trabajos exclusivamente fotográficos y de limpieza no crean una vía para evitar el registro. No existe una vía separada de apoyo sin reparación salvo que la Oficina de Protección al Consumidor del Condado de Montgomery (OCP) confirme por escrito su clasificación exacta y Tuveloz documente todos los demás requisitos aplicables.</p></section>
<section><h2>8. Prohibiciones estrictas para niveles provisionales</h2>
<p>Las cuentas que solo han presentado una solicitud, aprendices sin patrocinio, independientes provisionales y cualquier persona sin el conjunto completo de requisitos aprobados del servicio no deben realizar ni afirmar que pueden realizar:</p>
<ul><li>Trabajos de frenos, dirección, suspensión, transmisión, componentes internos del motor, sistema de combustible, bolsas de aire/SRS, ADAS, inmovilizadores, soldadura, estructura o sistemas eléctricos críticos para la seguridad.</li>
<li>Reparación, montaje o balanceo de llantas, evaluación de ruedas dañadas o transporte o eliminación no aprobados de llantas desechadas.</li>
<li>Trabajos en circuitos de refrigerante sin los requisitos de la sección 609 de la EPA y el equipo necesario.</li>
<li>Reparación de carrocería o pintura por pulverización, remolque o almacenamiento, apertura de vehículos cerrados, entrega de combustible o inspección oficial de seguridad o emisiones sin el proceso especializado completo.</li>
<li>Trabajos en baterías de tracción, inversores o cableado de alto voltaje de vehículos eléctricos o híbridos, vehículos eléctricos dañados, tensión activa o transporte de alto voltaje.</li>
<li>Cualquier tarea que no pueda identificarse mediante un código de servicio específico habilitado.</li></ul></section>
<section><h2>9. Asignación, supervisión y elección del cliente</h2>
<p>El negocio proveedor registrado debe aceptar y asignar el trabajo patrocinado, nunca el aprendiz ni Tuveloz directamente. La supervisión directa exige que el supervisor aprobado esté físicamente presente, haya registrado su llegada al mismo lugar de trabajo, pueda intervenir de inmediato y sea responsable de firmar los controles previos, intermedios, de finalización y del negocio proveedor. Un aprendiz no puede supervisar a otro aprendiz.</p>
<p>Antes de reservar, el cliente debe ver el negocio proveedor legal, la persona asignada, la denominación provisional o de patrocinio correcta, el servicio limitado exacto y sus exclusiones, la supervisión acordada y las pruebas específicas vigentes revisadas por Tuveloz. Incluso en el nivel inicial, la persona asignada debe contar con pruebas de competencia aceptadas para ese servicio exacto antes de la asignación. La aceptación informada del cliente de un proveedor con menos experiencia nunca elimina ese ni ningún otro requisito. Una denominación no garantiza habilidad, seguridad, precio, calidad del trabajo ni resultado. Una sustitución de persona requiere habilitación actualizada, información al cliente y aceptación afirmativa del cliente antes de iniciar el trabajo.</p></section>
<section><h2>10. Controles de trabajo, facturación, garantía, pagos y nómina</h2>
<p>Cada trabajo requiere una cotización o presupuesto escrito del servicio exacto y autorización afirmativa del cliente. El trabajo adicional requiere un código de servicio recién habilitado para ese trabajo, aprobación del proveedor, precio actualizado y aprobación del cliente. El negocio proveedor responsable debe emitir o aprobar los presupuestos, órdenes de cambio, facturas, identificación del mecánico, condiciones de garantía y registros de reparación, piezas y eliminación de residuos exigidos.</p>
<p>El trabajo patrocinado requiere la aprobación final del negocio proveedor antes de completarse o pagarse. Tuveloz paga al negocio proveedor, no al empleado que realiza el trabajo. El negocio sigue siendo responsable de su garantía y del pago de salarios mediante una nómina legal. Una persona de nivel inicial no puede realizar pruebas de conducción en un vehículo del cliente. Todo proceso de prueba aprobado debe utilizar a una persona habilitada y asegurada por separado y contar con los registros necesarios del cliente y del proveedor.</p></section>
<section><h2>11. Controles de seguro e incidentes</h2>
<p>El seguro debe corresponder al nombre del negocio proveedor, la persona que realiza el trabajo o categoría de trabajador, servicio exacto, lugar, uso del vehículo y fecha. Un certificado de seguro por sí solo no basta. La determinación del corredor guardada en el sistema debe abordar las coberturas aplicables de responsabilidad civil general, productos y operaciones terminadas, automóvil comercial, custodia de vehículos o cuidado/custodia/control, contaminación, compensación laboral, especialidades, límites, endosos y exclusiones.</p>
<p>Los proveedores deben informar inmediatamente lesiones, daños a vehículos o propiedad, incendios, derrames, amenazas de clientes, contactos con la policía, fallas de herramientas o equipos, piezas incorrectas, bienes perdidos y sospechas de peligro por combustible o alto voltaje. Deben conservarse los registros requeridos de cotización, autorización, mensajes, fotos, asignación, supervisión, pruebas, factura, garantía y aseguradora. El seguro del proveedor y el lenguaje contractual no eliminan las obligaciones legales o de seguro propias de Tuveloz.</p></section>
<section><h2>12. Avance, suspensión y registros</h2>
<p>El avance es específico de cada servicio, debe solicitarse y nunca es automático. Puede requerir formación, credenciales reconocidas, registros de trabajo supervisado, evaluación práctica, herramientas, equipo, controles de instalaciones y residuos, aprobación del seguro y un historial de conducta correcto. El tiempo en la plataforma por sí solo no prueba competencia.</p>
<p>El vencimiento o suspensión del negocio proveedor, persona asignada, registro laboral, registro comercial, seguro, supervisor o pruebas del servicio bloquea inmediatamente los trabajos que dependan de ellos. Tuveloz debe proporcionar una vía de corrección o apelación con criterios objetivos cuando corresponda, pero una apelación no restablece el acceso si sigue incumplido un requisito. Los eventos de habilitación, asignación, supervisión, cambios de alcance, finalización, incidentes y revisión deben conservar sus versiones exactas de políticas y registros auditables.</p></section>
<section><h2>13. Requisitos de aprobación</h2>
<p>Antes de activar cualquier servicio en producción, Tuveloz debe documentar y cumplir todos los requisitos aplicables legales, gubernamentales, de agencias, licencias, registros, permisos, privacidad, seguridad y del servicio específico. El corredor de seguros de Tuveloz debe aprobar la cobertura de la operación exacta, vías, límites y exclusiones. El contador público certificado o asesor fiscal cualificado y el procesador de pagos deben aprobar el proceso aplicable de impuestos, facturación, cargos y pagos al proveedor. Tuveloz debe obtener confirmación escrita de la OCP del Condado de Montgomery para clasificaciones de servicios controvertidas. Se recomienda revisión jurídica profesional independiente para asuntos complejos o controvertidos, pero no sustituye el cumplimiento de requisitos obligatorios.</p></section>`,
};

export default policy;
