/** Complete Spanish translation of app/provider-agreement/page.tsx. */
const policy = {
  title: "Acuerdo del proveedor",
  summary: "Condiciones en lenguaje claro para los negocios proveedores que trabajan a través de Tuveloz.",
  updated: "6 de agosto de 2026",
  html: `<section><h2>1. Estado de este documento y otras condiciones aplicables</h2>
<p>Este es un documento operativo, no un contrato legal definitivo, asesoramiento legal ni autorización para prestar todavía un servicio para vehículos a través de Tuveloz. El propietario de Tuveloz puede continuar por ahora sin un abogado particular, pero eso no reduce ningún requisito legal. Antes de habilitar un servicio, Tuveloz debe documentar y cumplir todos los requisitos federales, de Maryland, locales, de seguro, fiscales, de pagos, de privacidad y específicos del servicio que correspondan.</p>
<p>Este acuerdo se aplica junto con los <a href="/es/terms">Términos de uso</a>, la <a href="/es/marketplace-conduct">Política de conducta en el mercado</a>, la <a href="/es/provisional-provider-policy">Política de proveedores provisionales y aprendices</a>, la <a href="/es/privacy">Política de privacidad</a> y la <a href="/es/payments">Política de pagos, cancelaciones y reembolsos</a>.</p></section>
<section><h2>2. Su negocio y su relación con Tuveloz</h2>
<p>Usted es un negocio independiente, no un empleado, representante ni socio de Tuveloz. Nada de este acuerdo crea una relación laboral. Usted controla sus precios, horarios, herramientas, métodos, materiales y clientes. Tuveloz no contrata, emplea, capacita, patrocina, asigna, dirige, disciplina, supervisa ni incluye en su nómina a usted o a su personal, ni promete trabajos de clientes.</p>
<p>La aprobación para prestar un servicio para vehículos es distinta de la autorización para trabajar en Estados Unidos. Revisar una licencia, registro o seguro no establece autorización migratoria o laboral. Esa responsabilidad corresponde a usted o a su empleador, y Tuveloz no solicitará documentos migratorios salvo que la ley lo exija expresamente.</p></section>
<section><h2>3. Sin exclusividad ni obligación de aceptar trabajos</h2>
<p>Puede trabajar en otras plataformas o conseguir sus propios clientes; Tuveloz no exige exclusividad. Nunca está obligado a aceptar, cotizar ni completar un trabajo específico.</p></section>
<section><h2>4. Las tres formas de trabajar a través de Tuveloz</h2>
<h3>Propietario que realiza el trabajo por cuenta propia</h3><p>Solicita ingreso como su propio negocio establecido y realiza personalmente el trabajo. Es responsable de su registro, impuestos, configuración de cobros, seguro y requisitos del servicio exacto. Controla sus métodos, herramientas, horarios y precios.</p>
<h3>Aprendiz empleado con patrocinio</h3><p>Es un empleado remunerado real de un negocio proveedor registrado, y ese negocio, no usted, es el proveedor responsable del servicio. El negocio debe mantenerlo en su lista de personal, contar con compensación laboral y el seguro requerido, asignarle un supervisor habilitado y aprobar los controles obligatorios.</p>
<h3>Empleado habitual de un negocio proveedor</h3><p>Un negocio proveedor registrado también puede asignar a un empleado real que no sea aprendiz, siempre que figure en su lista de personal vigente y cuente con los registros laborales, de seguro y de competencia necesarios. Esta vía no permite omitir la supervisión de aprendices ni ningún otro requisito del servicio.</p>
<p>La relación real y la ley aplicable determinan su clasificación, independientemente del nombre que se le dé en este acuerdo. El personal del proveedor nunca es personal de Tuveloz, y ningún proveedor ni trabajador puede obligar a Tuveloz a asumir compromisos.</p></section>
<section><h2>5. No se permiten credenciales prestadas</h2>
<p>No puede tomar prestados, alquilar, compartir ni utilizar el registro, licencia, seguro, supervisor, cuenta o identidad verificada de otra persona para acceder a trabajos. La vía de aprendiz patrocinado no tiene una modalidad de contratista independiente o trabajador 1099. Un negocio patrocinador no puede incluir en su lista a un contratista ajeno para eludir obligaciones de registro, nómina, impuestos, seguro o supervisión.</p>
<p>Si no es un empleado real en una de las vías descritas, debe cumplir de manera independiente los requisitos como propietario que realiza el trabajo antes de realizar trabajos remunerados. Su habilitación está vinculada a usted, al servicio exacto, al lugar y a la fecha del trabajo. Nadie puede heredar las pruebas de otra persona.</p></section>
<section><h2>6. Todavía no hay servicios habilitados</h2>
<p>Todos los servicios específicos están desactivados. Ninguna solicitud, documento cargado, estado de cuenta o selección de un servicio candidato autoriza trabajos reales para clientes. Un servicio solo puede activarse después de documentar sus requisitos legales y gubernamentales, obtener de la aseguradora de Tuveloz la confirmación de cobertura para ese trabajo exacto y desarrollar y activar en producción los controles necesarios de evidencia, supervisión y seguridad.</p>
<p>Hasta entonces, el servicio permanece bloqueado en todas las etapas: búsqueda, cotización, reserva, inicio del trabajo y pago al proveedor. Una categoría amplia como «reparación general de automóviles» nunca sustituye a un servicio específico habilitado.</p></section>
<section><h2>7. Cómo gestionar sus trabajos</h2>
<p>Usted decide si busca una solicitud, fija o aprueba su cotización y controla cómo se realiza el trabajo conforme a la ley. Si el trabajo debe cambiar respecto de lo cotizado o las condiciones se vuelven inseguras, deténgase y obtenga la aprobación del cliente antes de continuar. Un aprendiz o empleado no puede ampliar el alcance, emitir una factura aparte, redirigir un pago ni prometer una garantía fuera del proceso de su negocio.</p>
<p>Las cotizaciones deben indicar claramente el servicio, alcance, horario, precio y supuestos sobre piezas. Nunca incluya piezas suministradas por el proveedor, reembolsos de piezas ni impuestos sobre piezas; el cliente las compra por su cuenta. Si cambia a la persona que realizará el trabajo, usted debe asegurarse de que esté habilitada, informar al cliente y obtener su aprobación cuando sea necesario.</p>
<p>Su negocio decide si ofrece una garantía de mano de obra; Tuveloz nunca la exige ni fija sus condiciones. Si la ofrece, indique sus condiciones exactas en la cotización —muchos talleres utilizan 12 meses o 12,000 millas como referencia— y cúmplala como promesa de su propio negocio. Si no la ofrece, la cotización lo indicará claramente y el cliente confirmará por escrito que lo contrata sin garantía. En ambos casos, la información sobre la garantía debe ser veraz; falsearla constituye un incumplimiento grave de estas condiciones.</p></section>
<section><h2>8. Sus responsabilidades</h2>
<p>Usted es el único responsable de realizar los servicios de forma segura y legal; contar con todas las licencias, registros, permisos o seguros exigidos legalmente para su servicio y lugar de trabajo; sus equipos y materiales; sus obligaciones fiscales, incluido el impuesto sobre el trabajo por cuenta propia; y los trabajadores o subcontratistas que utilice.</p>
<p>El seguro debe corresponder realmente a su negocio, su relación con los trabajadores, el servicio exacto, el lugar y la fecha del trabajo. Un certificado por sí solo no prueba la cobertura. Informe de inmediato cualquier interrupción de cobertura o incidente, como lesiones, daños materiales o problemas de seguridad.</p></section>
<section><h2>9. Qué le solicitamos</h2>
<p>Tuveloz solo solicitará documentos vinculados a un requisito legal específico de los servicios seleccionados. No pediremos documentos «por precaución» ni más de lo que la ley realmente exige.</p></section>
<section><h2>10. Información de los clientes</h2>
<p>Use los datos de contacto, vehículos, fotos o ubicación del cliente únicamente para cotizar, programar, realizar, documentar y apoyar su trabajo, o cuando la ley lo exija. No los venda, use para publicidad ajena al servicio, publique ni conserve más tiempo del razonablemente necesario. Usted es responsable del acceso y manejo de esos datos por su personal y de cumplir la <a href="/es/marketplace-conduct">Política de conducta en el mercado</a>.</p></section>
<section><h2>11. Pagos</h2>
<p>Recibe el precio completo de su cotización; el cargo del 5 % de Tuveloz se cobra por separado al cliente. El pago se libera después de marcar el trabajo como completado, se administra mediante Stripe y está sujeto a las revisiones de finalización y pago requeridas. Una transferencia puede retrasarse, revertirse o recuperarse por un reembolso, contracargo, fraude, asunto legal o error de pago. Ninguna de estas situaciones modifica sus responsabilidades de facturación, garantía o servicio.</p></section>
<section><h2>12. Impuestos</h2>
<p>Entregará un formulario W-9 completo al registrarse, y Tuveloz emitirá un formulario 1099 por los ingresos anuales que correspondan.</p></section>
<section><h2>13. Revisión, suspensión y terminación del acceso</h2>
<p>Puede dejar de usar Tuveloz en cualquier momento, sin penalización, plazo de aviso ni cargo, sin perjuicio de los trabajos, pagos o disputas pendientes.</p>
<p>Tuveloz también puede bloquear un servicio, una persona o su negocio mientras investiga una preocupación real sobre credenciales, seguro, seguridad, pagos o conducta, y puede retirar el acceso por incumplimientos graves o reiterados. Cuando sea práctico y jurídicamente apropiado, le explicaremos el motivo y le daremos una forma de responder. Una apelación no restablece el acceso si un requisito legal o de seguridad sigue sin cumplirse. La pérdida o el vencimiento de una credencial o seguro requerido bloquea de inmediato los trabajos que dependan de ellos.</p></section>
<section><h2>14. Si algo sale mal</h2>
<p>Usted acepta indemnizar a Tuveloz por reclamaciones derivadas de su trabajo, su negligencia o declaraciones inexactas sobre su experiencia, credenciales o seguro. Esto no se aplica al fraude o conducta dolosa de Tuveloz ni a responsabilidades que la ley no permita asumir. Nada de esto significa que Tuveloz carezca de responsabilidad propia: sigue siendo responsable de sus obligaciones de mercado, pagos y privacidad cuando la ley lo exija.</p></section>
<section><h2>15. Condiciones que continúan vigentes</h2>
<p>Los ajustes de pagos, obligaciones fiscales, confidencialidad, límites de uso de datos de clientes, responsabilidades de garantía, cooperación ante incidentes y condiciones sobre disputas siguen aplicándose después de dejar de usar Tuveloz. Si este acuerdo entra en conflicto con los Términos de uso generales en un asunto específico de proveedores, prevalece este acuerdo.</p></section>`,
};

export default policy;
