/** Complete Spanish translation of app/terms/page.tsx; no policy changes. */
const policy = {
  title: "Términos de uso",
  summary: "Condiciones en lenguaje claro para usar el mercado de servicios para vehículos de Tuveloz.",
  updated: "7 de agosto de 2026",
  html: `<section><h2>Situación actual</h2>
<p>Tuveloz está actualmente en la etapa de revisión de solicitudes de proveedores, no de uso general. Todavía no hay ningún servicio habilitado para trabajos reales de clientes, y los clientes no pueden publicar, reservar, pagar, iniciar ni completar un trabajo real, ni liberar su pago al proveedor, a través de la plataforma. Cada servicio permanece desactivado hasta que se documenten y cumplan sus requisitos legales, de seguro y técnicos. Esta página describe cómo funciona Tuveloz una vez habilitado un servicio y se aplica plenamente cuando lo utiliza.</p>
<p>Estos Términos son un documento operativo; no sustituyen el asesoramiento legal ni constituyen prueba de cumplimiento. El propietario de Tuveloz puede decidir continuar por ahora sin un abogado particular, pero esa decisión no reduce ninguna obligación que la ley imponga a Tuveloz.</p></section>
<section><h2>1. A quiénes se aplican</h2>
<p>Estos Términos se aplican desde que crea una cuenta, publica un trabajo, envía una cotización o utiliza Tuveloz de cualquier otra forma. Si es cliente, también se aplica el <a href="/customer-agreement">Acuerdo del cliente (en inglés)</a>. Si es proveedor, también se aplica el <a href="/es/provider-agreement">Acuerdo del proveedor</a>. También se aplican la <a href="/es/privacy">Política de privacidad</a>, la <a href="/es/payments">Política de pagos, cancelaciones y reembolsos</a>, la <a href="/copyright">Política de derechos de autor y DMCA (en inglés)</a> y, si acepta recibir mensajes de texto, los <a href="/sms-terms">Términos de SMS (en inglés)</a>.</p>
<p>Debe tener al menos 18 años, capacidad para celebrar un acuerdo vinculante y autorización para actuar en nombre de cualquier persona o negocio que represente. Si no cumple estas condiciones, no utilice Tuveloz.</p></section>
<section><h2>2. Tuveloz es un mercado, no un proveedor de servicios</h2>
<p>Tuveloz conecta a clientes con negocios independientes que prestan servicios para vehículos. Tuveloz no realiza, supervisa ni garantiza ningún servicio para vehículos, y no contrata, emplea, capacita, patrocina, asigna, dirige, disciplina ni supervisa a proveedores, mecánicos, aprendices o empleados de negocios proveedores. El negocio proveedor acepta el trabajo, controla a su propio personal y realiza el servicio bajo su propio nombre.</p>
<p>Una vez habilitado un servicio, la aceptación de una cotización crea un acuerdo directo entre el cliente y el negocio proveedor; Tuveloz no es parte de ese acuerdo. Los clientes deciden a quién contratar. Los proveedores deciden qué trabajos buscar, cuánto cotizar y cómo realizar el trabajo conforme a la ley. El uso de Tuveloz por sí solo no crea una relación laboral, de representación, sociedad o franquicia entre usuarios. La situación jurídica real depende de los hechos, no de las denominaciones de estos Términos.</p></section>
<section><h2>3. El acuerdo entre usted y la otra parte</h2>
<p>Cuando un cliente acepta una cotización, el cliente y el proveedor celebran su propio acuerdo de servicio sobre el alcance de la mano de obra, el precio, el lugar, el horario y los cambios que aprueben posteriormente. Una nota del proveedor sobre piezas originales del fabricante o de otros fabricantes es una comunicación acerca de piezas que el cliente compra por separado; nunca constituye una venta ni un pago de piezas a través de Tuveloz.</p>
<p>Tuveloz no se convierte en parte de ese acuerdo por mostrar información, facilitar mensajes, cobrar el cargo de servicio al cliente o ayudar a revisar una queja. Nadie puede hacer promesas ni firmar documentos en nombre de Tuveloz.</p></section>
<section><h2>4. Qué verifica Tuveloz</h2>
<p>Tuveloz confirma únicamente la licencia, el registro o el seguro específicos que la ley exige para un servicio determinado, y nada más. No existe una sola credencial que cubra todo tipo de trabajo en vehículos, por lo que la revisión depende del servicio exacto y del lugar. Tuveloz no afirma que un proveedor esté «certificado», «verificado» o «asegurado» más allá de lo documentado y divulgado para ese servicio. Los proveedores no pueden tomar prestadas, compartir ni utilizar credenciales ajenas para obtener acceso a trabajos.</p>
<p>Tuveloz no realiza investigaciones de antecedentes penales de proveedores, empleados o aprendices, y aparecer en Tuveloz no constituye un aval de su conducta personal. Si Tuveloz incorpora alguna revisión para un servicio específico, esta página describirá exactamente qué se revisa, sin atribuirle un alcance mayor.</p>
<p>En esta etapa de solicitudes de proveedores, ningún servicio está habilitado para trabajos reales. Un servicio solo avanza después de documentar y cumplir sus requisitos legales y activar deliberadamente los controles correspondientes.</p></section>
<section><h2>5. Uso responsable de Tuveloz</h2>
<p>Proporcione información correcta y actualizada, y use Tuveloz únicamente para solicitudes lícitas de servicios para vehículos. No suplante identidades, publique trabajos que no pueda autorizar, falsee credenciales, precios, reseñas o trabajos realizados, acose ni discrimine ilegalmente, interfiera con la seguridad de la plataforma, extraiga datos privados, cargue programas maliciosos ni utilice Tuveloz para cometer fraude o realizar trabajos inseguros o ilegales.</p>
<p>Mantenga en privado su contraseña, los códigos de un solo uso y el acceso a su cuenta. Avísenos de inmediato si cree que alguien pudo acceder a su cuenta sin autorización.</p></section>
<section><h2>6. Cotizaciones, cambios y garantías</h2>
<p>Los proveedores fijan sus propias cotizaciones de mano de obra y deben describir claramente el alcance, los supuestos sobre piezas, los plazos, las exclusiones y el precio. Las cotizaciones, facturas y pagos de Tuveloz nunca incluyen piezas suministradas por el proveedor, reembolsos de piezas ni impuestos sobre piezas. El cliente compra por separado cualquier pieza necesaria. Cualquier trabajo o precio adicional a la cotización aceptada requiere primero la aprobación del cliente.</p>
<p>Cada negocio proveedor independiente decide si ofrece una garantía de mano de obra; Tuveloz nunca la exige ni fija sus condiciones. Cada cotización muestra las condiciones escritas de la garantía del proveedor o una declaración clara de que no se ofrece ninguna. El cliente que elija un proveedor sin garantía reconoce expresamente esa elección antes de contratarlo. Toda garantía ofrecida por un proveedor es una promesa de ese negocio al cliente; Tuveloz no ofrece, respalda ni administra una garantía por el mero hecho de operar el mercado. Nada de lo aquí indicado elimina garantías o derechos irrenunciables conforme a la ley.</p></section>
<section><h2>7. Cargos</h2>
<p>Cuando se habilite el servicio, Tuveloz prevé cobrar un cargo del 5 % sobre los trabajos completados, que se añadirá al precio cotizado por el proveedor y se mostrará al cliente antes de aceptar. No hay cargos por explorar, publicar una solicitud, solicitar ingreso como proveedor ni enviar una cotización. Ese 5 % es el precio propuesto por Tuveloz; todavía requiere la aprobación final de un asesor fiscal, el procesador de pagos y el corredor de seguros de Tuveloz.</p>
<p>Una vez habilitados los pagos, se regirán por la <a href="/es/payments">Política de pagos, cancelaciones y reembolsos</a>, incluidas las reglas sobre reembolsos, disputas y contracargos. Operar un sistema de pagos no convertiría a Tuveloz en proveedor del servicio para vehículos ni eliminaría las obligaciones de pago que la ley imponga directamente a Tuveloz.</p></section>
<section><h2>8. Contenido y reseñas</h2>
<p>Usted conserva la propiedad de lo que publica. Autoriza a Tuveloz a alojar, copiar, cambiar de tamaño, mostrar y compartir ese contenido únicamente según sea necesario para operar la plataforma y cualquier página pública de proveedor que decida publicar, y solo si realmente tiene derecho a compartirlo.</p>
<p>Las reseñas deben reflejar una experiencia real. No cargue credenciales de pago, documentos de identidad innecesarios, rostros, direcciones ni matrículas visibles. Tuveloz puede retirar contenido ilegal, engañoso, inseguro o que invada la privacidad de alguien.</p></section>
<section><h2>9. Seguridad</h2>
<p>Tuveloz no es un servicio de emergencia, despacho de grúas, rescate en carretera, policía, bomberos ni atención médica. Elija un lugar permitido y razonablemente seguro para el trabajo, y deténgalo si las condiciones se vuelven inseguras. Una opinión de diagnóstico o de compra de un vehículo no constituye una inspección gubernamental oficial, salvo que el proveedor indique expresamente que lo es.</p></section>
<section><h2>10. Suspensión o terminación del acceso</h2>
<p>Puede dejar de usar Tuveloz en cualquier momento, sin perjuicio de los trabajos, pagos o disputas pendientes. Tuveloz puede restringir, suspender o terminar su acceso para proteger a los usuarios o la plataforma, investigar una preocupación real, atender una credencial vencida o inválida, cumplir la ley o las reglas de las redes de pago, o responder a un incumplimiento grave de estos Términos. Cuando sea práctico y jurídicamente apropiado, le explicaremos el motivo y le daremos la oportunidad de responder.</p></section>
<section><h2>11. Exclusiones de garantías</h2>
<p>Si se adopta, la plataforma se proporciona «tal cual» y «según disponibilidad». Tuveloz no promete acceso ininterrumpido, una cantidad determinada de cotizaciones, la exactitud de las declaraciones de los usuarios ni un resultado concreto del trabajo de un proveedor. Usted decide qué persona y qué servicio son adecuados para sus necesidades. Nada de lo aquí indicado elimina un derecho irrenunciable conforme a la ley.</p></section>
<section><h2>12. Responsabilidad e indemnización</h2>
<p>La función de Tuveloz se limita a operar el mercado. En la máxima medida permitida por la ley de Maryland, la responsabilidad de Tuveloz por una reclamación se limita al cargo de servicio al cliente cobrado por el trabajo al que se refiere la reclamación. Este límite no elimina ningún derecho, obligación o recurso irrenunciable conforme a la ley, ni afirma que Tuveloz carezca de toda responsabilidad.</p>
<p>Si un tercero presenta una reclamación contra Tuveloz por una acción suya —como publicar contenido sin derecho a compartirlo, solicitar un trabajo sin autorización, falsear credenciales o condiciones de garantía, infringir una ley o realizar un servicio a través de su negocio—, usted acepta defender a Tuveloz y cubrir los honorarios legales, costos y daños razonables derivados de esa reclamación. Esto no se aplica a la parte causada por la propia conducta de Tuveloz. Tuveloz le informará con prontitud de cualquier reclamación cuya cobertura le solicite. Nada de lo aquí indicado renuncia a derechos que la ley no permita renunciar.</p></section>
<section><h2>13. Resolución de disputas con Tuveloz</h2>
<p>Antes de presentar una reclamación contra Tuveloz, escriba a <a href="mailto:hello@tuveloz.com">hello@tuveloz.com</a> para explicar lo ocurrido y lo que solicita. Concédanos 60 días para intentar resolverlo informalmente. Esto no amplía ningún plazo legal que tenga para presentar una reclamación.</p>
<p>Estos Términos no exigen arbitraje. Si no podemos resolver una disputa informalmente, tanto usted como Tuveloz pueden acudir a los tribunales, incluido el tribunal de reclamos menores cuando corresponda. Nada de lo aquí indicado implica renunciar a un juicio por jurado ni al derecho a plantear inquietudes ante una agencia gubernamental. Esta sección solo cubre disputas con Tuveloz; las disputas entre cliente y proveedor se rigen por su propio acuerdo de servicio.</p>
<p>Estos Términos se rigen por la ley de Maryland, excluidas sus normas sobre conflictos de leyes. Toda reclamación entre usted y Tuveloz debe presentarse ante los tribunales estatales o federales con jurisdicción sobre el Condado de Montgomery, Maryland, y ambas partes aceptan su jurisdicción. Nada de esta sección renuncia a derechos irrenunciables conforme a la ley.</p></section>
<section><h2>14. Cambios en estos Términos</h2>
<p>Publicaremos los cambios importantes con una nueva fecha y le pediremos que los acepte otra vez antes de una nueva transacción cuando la ley lo exija. Un cambio no modificará un acuerdo de servicio ya aceptado, salvo que ambas partes lo acuerden o la ley lo exija.</p>
<p>Si alguna parte de estos Términos resulta inaplicable, el resto seguirá vigente. No exigir el cumplimiento de una disposición en una ocasión no implica renunciar a ella.</p></section>`,
};

export default policy;
