export type EvidenceLanguage = "en" | "es";

const spanish: Record<string, string> = {
  "Document": "Documento",
  "Choose document": "Elegir documento",
  "No document chosen": "No ha elegido un documento",
  "PDF, JPG, PNG, or WebP; up to 3.5 MB per document. Larger photos are resized on your device before upload.": "PDF, JPG, PNG o WebP; hasta 3.5 MB por documento. Las fotos más grandes se reducen en su dispositivo antes de enviarlas.",
  "Your document stays private and is checked for harmful files before review.": "Su documento se mantiene privado y se revisa para detectar archivos dañinos antes de evaluar su contenido.",
  "Issuer or source": "Entidad emisora o fuente",
  "Insurer, agency, school, or business": "Aseguradora, agencia, escuela o empresa",
  "Effective date": "Fecha de inicio de vigencia",
  "Expiration date": "Fecha de vencimiento",
  "Expiration date (required)": "Fecha de vencimiento (obligatoria)",
  "Photo resized. Check that the whole document is clear before uploading.": "Foto reducida. Revise que el documento completo se vea claro antes de enviarlo.",
  "Resized document preview": "Vista previa del documento reducido",
  "Open full-size preview": "Abrir vista previa en tamaño completo",
  "The whole document is clear and readable.": "El documento completo se ve claro y se puede leer.",
  "Preparing photo…": "Preparando foto…",
  "Uploading…": "Enviando…",
  "Upload corrected replacement": "Enviar documento corregido",
  "Upload document": "Enviar documento",
  "Choose a PDF, JPG, PNG, or WebP document.": "Elija un documento PDF, JPG, PNG o WebP.",
  "Upload a PDF, JPG, PNG, or WebP document.": "Envíe un documento PDF, JPG, PNG o WebP.",
  "The document must be 3.5 MB or smaller.": "El documento debe tener un tamaño de 3.5 MB o menos.",
  "This PDF is over 3.5 MB. Choose a smaller PDF from the issuer, keeping every page. If you need help, contact hello@tuveloz.com.": "Este PDF supera los 3.5 MB. Elija un PDF más pequeño de la entidad emisora que incluya todas las páginas. Si necesita ayuda, escriba a hello@tuveloz.com.",
  "This photo is over 20 MB. Choose a smaller photo or a PDF under 3.5 MB.": "Esta foto supera los 20 MB. Elija una foto más pequeña o un PDF de menos de 3.5 MB.",
  "We couldn't prepare this photo. Choose a JPG, PNG, or WebP photo, or a PDF under 3.5 MB.": "No pudimos preparar esta foto. Elija una foto JPG, PNG o WebP, o un PDF de menos de 3.5 MB.",
  "We couldn't make this photo small enough while keeping enough detail. Try a closer photo of the whole document, or a PDF under 3.5 MB.": "No pudimos reducir esta foto lo suficiente sin perder detalle. Intente tomar una foto más cercana del documento completo o elija un PDF de menos de 3.5 MB.",
  "Unable to prepare this document.": "No pudimos preparar este documento. Inténtelo de nuevo.",
  "Unable to upload this evidence.": "No pudimos enviar este documento. Inténtelo de nuevo.",
  "Uploaded privately for scanning and review.": "Documento enviado de forma privada para revisar su seguridad y contenido.",
  "Your document was uploaded. Refresh the page to see its status.": "Su documento ya se envió. Actualice la página para ver su estado.",
  "The file contents do not match the selected document type.": "El contenido del archivo no coincide con el tipo de documento seleccionado.",
  "Sign in with your provider account.": "Inicie sesión con su cuenta de proveedor.",
  "This upload must come from TUVELOZ.": "Envíe este documento desde el sitio de Tuveloz.",
  "Choose a recognized exact service.": "Elija un servicio específico de la lista.",
  "That service is not on this application.": "Ese servicio no está incluido en esta solicitud.",
  "That evidence type is not required for this service and pathway.": "Este tipo de documento no se requiere para el servicio y la modalidad seleccionados.",
  "Applicant-only accounts receive no training or jobs and cannot submit job-eligibility documents until a real provider pathway is selected.": "Las cuentas de solicitantes no reciben capacitación ni trabajos. Para enviar documentos de elegibilidad, primero debe seleccionar la modalidad que corresponde a su situación real como proveedor.",
  "This requirement must be confirmed through the employer, supervisor, or TUVELOZ workflow. Do not upload work-authorization documents, SSNs, or I-9 records.": "Este requisito debe confirmarse con el empleador, supervisor o proceso de revisión de Tuveloz. No envíe documentos de autorización de trabajo, números de Seguro Social ni formularios I-9.",
  "This evidence already has a submission under review.": "Ya hay un documento enviado para este requisito que está en revisión.",
  "Upload the new document as a replacement from the existing evidence record so review history is preserved.": "Envíe el nuevo documento como reemplazo desde el registro existente para conservar el historial de revisión.",
  "The replacement must match your own prior evidence, exact service, person, and jurisdiction.": "El reemplazo debe corresponder a su documento anterior y al mismo servicio, persona y jurisdicción.",
  "Wait for the current submission review before uploading another replacement.": "Espere a que se revise el documento actual antes de enviar otro reemplazo.",
  "A replacement for this evidence is already under review.": "Ya hay un reemplazo de este documento en revisión.",
  "Enter valid evidence details and dates.": "Revise los datos y las fechas del documento.",
  "This evidence type requires an expiration date.": "Este tipo de documento requiere una fecha de vencimiento.",
  "The expiration date must be after the effective date.": "La fecha de vencimiento debe ser posterior a la fecha de inicio de vigencia.",
  "Upload current evidence that has not already expired.": "Envíe un documento vigente que no haya vencido.",
};

export function evidenceText(value: string, language: EvidenceLanguage) {
  return language === "es" ? spanish[value] ?? value : value;
}
